# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4bvZ8ED8gO8MsgGJsgUQEmdGL-P7pD8
"""

"""
DF26 — EDA CHUYÊN SÂU (PHIÊN BẢN ĐẦY ĐỦ)
==========================================
Phân tách nghiêm ngặt train / validation.
Bao gồm:
  1.  Quy mô và cấu trúc dữ liệu
  2.  Distribution shift: độ dài chuỗi
  3.  Phân tích token đặc biệt (102-115, 609, large codes)
  4.  Regime (0/1/2) và shift cực mạnh sang test
  5.  Boss regime (regime 2) deep dive
  6.  Large code (>10 000) → attr_3 / attr_6 analysis
  7.  Positional analysis: prefix / middle / suffix → target
  8.  Rule memory evaluation: coverage & accuracy train→val
  9.  Target distribution, drift, correlation
  10. Duplicate / conflict / label quality
  11. Hàm ý mô hình hóa
  Sinh: JSON summary, 10 biểu đồ, báo cáo Markdown.
"""

import os
import json
import math
import warnings
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

warnings.filterwarnings("ignore")

# ============================================================
# CONFIG
# ============================================================
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_CANDIDATES = [
    os.getenv("DATA_DIR", ""),
    str(SCRIPT_DIR),
    str(Path.cwd()),
    "/content/sample_data", "sample_data", "/mnt/data",
    "/mnt/user-data/uploads", ".",
]
OUT_DIR = "eda_outputs_df26_deep"

TARGET_COLS  = [f"attr_{i}" for i in range(1, 7)]
M_NORM       = np.array([12, 31, 99, 12, 31, 99], dtype=np.float32)
W_METRIC     = np.array([1,  1, 100,  1,  1, 100], dtype=np.float32)

# --- Special token taxonomy ---
# Tier-1 structural tokens (never appear as regular action codes)
STRUCT_TOKENS = {
    102: "SEP_START  — bắt đầu phân đoạn mới (tiền tố của 103)",
    103: "SEP_MAIN   — token phân đoạn chính, tách prefix khỏi suffix",
    104: "END_BOSS   — token kết thúc đặc biệt, định nghĩa regime boss",
    105: "HEADER_B   — token header nhóm B, hay xuất hiện sau 103",
}
# Tier-2 context/flag tokens
FLAG_TOKENS = {
    97: "FLAG_97", 106: "FLAG_106", 107: "FLAG_107", 108: "FLAG_108",
    109: "FLAG_109 → attr_1=3 perfect",
    110: "FLAG_110", 111: "FLAG_111 → attr_1=5 perfect",
    112: "FLAG_112", 113: "FLAG_113", 114: "FLAG_114", 115: "FLAG_115",
}
# Tier-3 routing tokens (determine regime / segment entry point)
ROUTE_TOKENS = {
    609: "ROUTE_609 — luôn đứng đầu chuỗi regime 1; khi xuất hiện → mode 'no-split'",
}
ALL_SPECIAL = list(STRUCT_TOKENS) + list(FLAG_TOKENS) + list(ROUTE_TOKENS)

LARGE_THRESH = 10_000   # mã sản phẩm / nhà máy
SMALL_THRESH = 200      # action-type codes

# Top large codes với business meaning (từ EDA)
LARGE_CODE_KNOWN = {
    21040: "LC_21040 → mean attr_3≈72.7 (nhà máy tải cao)",
    17980: "LC_17980 → mean attr_3≈68.1",
    21606: "LC_21606 → mean attr_3≈62.4",
    20278: "LC_20278 → mean attr_3≈57.4",
    15342: "LC_15342 → mean attr_3≈52.3",
    20022: "LC_20022 → mean attr_3≈42.1",
    15881: "LC_15881 → mean attr_3≈23.1 (nhà máy tải thấp)",
    24438: "LC_24438 → mean attr_3≈10.0 (nhà máy nghỉ/rỗng)",
}

# Perfect-predictor feature_1 codes (from ablation)
PERFECT_F1 = {
    760: 12, 685: 11, 836: 5, 111: 5, 12516: 9,
    10686: 8, 109: 3, 7943: 3, 10477: 3, 164: 1,
}


# ============================================================
# UTILITIES
# ============================================================
def find_data_dir():
    required = ["X_train.csv", "X_val.csv", "X_test.csv", "Y_train.csv", "Y_val.csv"]
    for d in DATA_CANDIDATES:
        if all(os.path.exists(os.path.join(d, f)) for f in required):
            return d
    raise FileNotFoundError("Dataset folder not found")

def ensure_dir(p): Path(p).mkdir(parents=True, exist_ok=True)

def savefig(path, dpi=160):
    plt.tight_layout()
    plt.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close("all")

def pct(x): return f"{100*x:.2f}%"
def fmt(x, nd=3):
    if isinstance(x, (int, np.integer)): return f"{int(x):,}"
    return f"{x:,.{nd}f}"

def get_rows_lens(df, feat_cols):
    arr = df[feat_cols].fillna(0).astype(np.int64).to_numpy()
    rows, lens = [], []
    for r in arr:
        row = [int(v) for v in r if v != 0]
        rows.append(row)
        lens.append(len(row))
    return rows, np.array(lens, dtype=np.int64)

def get_regime(row):
    if 103 in row: return 0
    if 104 in row: return 2
    return 1

def strip104(row):
    return row[:-1] if len(row) > 0 and row[-1] == 104 else row

def build_vocab(rows):
    s = set()
    for r in rows: s.update(r)
    return s

def total_variation(a, b):
    idx = sorted(set(a.index) | set(b.index))
    pa = np.array([a.get(i, 0.0) for i in idx], dtype=np.float64)
    pb = np.array([b.get(i, 0.0) for i in idx], dtype=np.float64)
    return 0.5 * np.abs(pa - pb).sum()

def weighted_score(y_true, y_pred):
    err = ((y_true.astype(np.float32) - y_pred.astype(np.float32)) / M_NORM) ** 2
    return float(np.mean(np.sum(err * W_METRIC, axis=1) / 6.0))

def token_presence(rows, token):
    return float(sum(token in r for r in rows) / max(1, len(rows)))

def majority_rule(train_rows, y_vals, key_fn):
    bucket = defaultdict(list)
    for r, yy in zip(train_rows, y_vals):
        k = key_fn(r)
        if k is None: continue
        bucket[k].append(int(yy))
    out = {}
    for k, vals in bucket.items():
        cnt = Counter(vals)
        pred, n = cnt.most_common(1)[0]
        out[k] = (pred, n / len(vals), len(vals))
    return out

def eval_rule(val_rows, y_val, lookup, key_fn, min_n=3, min_purity=0.95):
    covered = correct = 0
    for r, y in zip(val_rows, y_val):
        k = key_fn(r)
        if k is None or k not in lookup: continue
        pred, pur, n = lookup[k]
        if n < min_n or pur < min_purity: continue
        covered += 1
        correct += int(pred == int(y))
    return {
        "coverage": covered / max(1, len(val_rows)),
        "accuracy_on_covered": correct / max(1, covered),
        "covered_rows": int(covered),
    }

def pospair_lookup(rows, y_vals, positions, rev=False):
    bucket = defaultdict(list)
    for r, yy in zip(rows, y_vals):
        L = len(r)
        idxs, ok = [], True
        for p in positions:
            idx = L - p if rev else p
            if idx < 0 or idx >= L: ok = False; break
            idxs.append(idx)
        if not ok: continue
        bucket[tuple(r[j] for j in idxs)].append(int(yy))
    out = {}
    for k, vals in bucket.items():
        cnt = Counter(vals)
        best, n = cnt.most_common(1)[0]
        out[k] = (best, n / len(vals), len(vals))
    return out


# ============================================================
# SECTION 1 — LOAD
# ============================================================
def load_data(data_dir):
    X_train = pd.read_csv(os.path.join(data_dir, "X_train.csv"))
    X_val   = pd.read_csv(os.path.join(data_dir, "X_val.csv"))
    X_test  = pd.read_csv(os.path.join(data_dir, "X_test.csv"))
    Y_train = pd.read_csv(os.path.join(data_dir, "Y_train.csv"))
    Y_val   = pd.read_csv(os.path.join(data_dir, "Y_val.csv"))
    feat_cols = [c for c in X_train.columns if c.startswith("feature_")]
    return X_train, X_val, X_test, Y_train, Y_val, feat_cols


# ============================================================
# SECTION 2 — SPECIAL TOKEN DEEP ANALYSIS
# ============================================================
def analyze_special_tokens(rows_tr, rows_va, rows_te, y_tr, y_va):
    """
    Phân tích chi tiết từng nhóm token đặc biệt:
      - Position analysis (vị trí xuất hiện trong chuỗi)
      - Co-occurrence với token khác
      - Predictive power đối với từng target
      - Presence shift qua train/val/test
    """
    results = {}

    for split_name, rows in [("train", rows_tr), ("val", rows_va), ("test", rows_te)]:
        presence = {}
        for tok in ALL_SPECIAL:
            n_has = sum(1 for r in rows if tok in r)
            n_first = sum(1 for r in rows if len(r) > 0 and r[0] == tok)
            n_last  = sum(1 for r in rows if len(r) > 0 and r[-1] == tok)
            # Mean position when present (normalized by seq length)
            positions = []
            for r in rows:
                for i, v in enumerate(r):
                    if v == tok:
                        positions.append(i / max(1, len(r) - 1))
            presence[tok] = {
                "pct_has": n_has / max(1, len(rows)),
                "pct_first": n_first / max(1, len(rows)),
                "pct_last": n_last / max(1, len(rows)),
                "mean_rel_position": float(np.mean(positions)) if positions else None,
                "n_occurrences": len(positions),
            }
        results[split_name] = presence

    # Predictive power of structural tokens on train
    tok_pred = {}
    for tok in list(STRUCT_TOKENS) + list(ROUTE_TOKENS):
        has_tok = [i for i, r in enumerate(rows_tr) if tok in r]
        no_tok  = [i for i, r in enumerate(rows_tr) if tok not in r]
        if not has_tok or not no_tok:
            continue
        stats = {}
        for j, col in enumerate(TARGET_COLS):
            y_has = y_tr[has_tok, j]
            y_no  = y_tr[no_tok, j]
            stats[col] = {
                "mean_has": float(np.mean(y_has)),
                "mean_no":  float(np.mean(y_no)),
                "diff":     float(np.mean(y_has) - np.mean(y_no)),
            }
        tok_pred[tok] = stats

    # 103 position analysis: where is last 103 in sequence?
    pos103_rel = []
    for r in rows_tr:
        p103 = [i for i, v in enumerate(r) if v == 103]
        if p103:
            pos103_rel.append(p103[-1] / max(1, len(r) - 1))
    results["pos103_relative_distribution"] = {
        "mean": float(np.mean(pos103_rel)) if pos103_rel else None,
        "median": float(np.median(pos103_rel)) if pos103_rel else None,
        "pct_in_first_half": float(np.mean([p < 0.5 for p in pos103_rel])) if pos103_rel else None,
    }

    # 104 position in boss sequences
    boss_tr = [r for r in rows_tr if 103 not in r and 104 in r]
    pos104_rel = [r.index(104) / max(1, len(r) - 1) for r in boss_tr if 104 in r]
    results["boss_104_position"] = {
        "n_boss": len(boss_tr),
        "pct_104_at_last": float(np.mean([r[-1] == 104 for r in boss_tr])),
        "mean_relative_pos": float(np.mean(pos104_rel)) if pos104_rel else None,
    }

    # 609 routing: always first?
    route609_tr = [r for r in rows_tr if 609 in r]
    results["token_609_routing"] = {
        "n_has_609": len(route609_tr),
        "pct_609_first": float(np.mean([r[0] == 609 for r in route609_tr])) if route609_tr else 0.0,
        "pct_no_103_when_609": float(np.mean([103 not in r for r in route609_tr])) if route609_tr else 0.0,
        "pct_no_104_when_609": float(np.mean([104 not in r for r in route609_tr])) if route609_tr else 0.0,
    }

    # perfect-predictor feature_1 codes
    perfect_f1_stats = {}
    for code, month in PERFECT_F1.items():
        rows_with = [i for i, r in enumerate(rows_tr) if len(r) > 0 and r[0] == code]
        if rows_with:
            a1_vals = y_tr[rows_with, 0]
            perfect_f1_stats[code] = {
                "predicted_month": month,
                "n_train": len(rows_with),
                "accuracy": float(np.mean(a1_vals == month)),
                "unique_a1_values": sorted(set(int(v) for v in a1_vals)),
            }
    results["perfect_f1_predictors"] = perfect_f1_stats

    return results


# ============================================================
# SECTION 3 — LARGE CODE ANALYSIS
# ============================================================
def analyze_large_codes(rows_tr, rows_va, rows_te, y_tr, y_va):
    """
    Large codes (>10 000) là mã sản phẩm / nhà máy.
    Chứng minh chúng predict mạnh attr_3 và attr_6.
    """
    # Collect frequency of each large code
    large_freq_tr = Counter(v for r in rows_tr for v in r if v > LARGE_THRESH)
    large_freq_te = Counter(v for r in rows_te for v in r if v > LARGE_THRESH)

    # For each large code: mean/std of attr_3 and attr_6
    code_stats_tr = defaultdict(list)
    for i, r in enumerate(rows_tr):
        for v in r:
            if v > LARGE_THRESH:
                code_stats_tr[v].append((int(y_tr[i, 2]), int(y_tr[i, 5])))

    code_summary_tr = {}
    for code, pairs in code_stats_tr.items():
        if len(pairs) < 20:
            continue
        a3 = [p[0] for p in pairs]
        a6 = [p[1] for p in pairs]
        code_summary_tr[code] = {
            "n": len(pairs),
            "attr3_mean": float(np.mean(a3)),
            "attr3_std":  float(np.std(a3)),
            "attr6_mean": float(np.mean(a6)),
            "attr6_std":  float(np.std(a6)),
        }

    # Same for val — check consistency
    code_stats_va = defaultdict(list)
    for i, r in enumerate(rows_va):
        for v in r:
            if v > LARGE_THRESH:
                code_stats_va[v].append((int(y_va[i, 2]), int(y_va[i, 5])))

    # Cross-split consistency: how stable is mean attr_3 per large code?
    common_codes = set(code_summary_tr.keys()) & {c for c, p in code_stats_va.items() if len(p) >= 10}
    consistency = {}
    for code in sorted(common_codes):
        va_a3 = [p[0] for p in code_stats_va[code]]
        tr_mean = code_summary_tr[code]["attr3_mean"]
        va_mean = float(np.mean(va_a3))
        consistency[code] = {
            "tr_mean_a3": tr_mean,
            "va_mean_a3": va_mean,
            "abs_diff": abs(tr_mean - va_mean),
        }

    # first_large_code in sequence: does it predict attr_3?
    first_large_lkp = defaultdict(list)
    for i, r in enumerate(rows_tr):
        for v in r:
            if v > LARGE_THRESH:
                first_large_lkp[v].append(int(y_tr[i, 2]))
                break

    # Presence of ANY large code: correlation with attr_3
    has_large_tr = np.array([any(v > LARGE_THRESH for v in r) for r in rows_tr])
    corr_large_a3 = np.corrcoef(has_large_tr.astype(float), y_tr[:, 2])[0, 1]
    corr_large_a6 = np.corrcoef(has_large_tr.astype(float), y_tr[:, 5])[0, 1]

    n_large_tr = np.array([sum(1 for v in r if v > LARGE_THRESH) for r in rows_tr])
    corr_nlarge_a3 = np.corrcoef(n_large_tr.astype(float), y_tr[:, 2])[0, 1]

    return {
        "top20_by_freq_train": large_freq_tr.most_common(20),
        "top20_by_freq_test":  large_freq_te.most_common(20),
        "n_unique_large_train": len(large_freq_tr),
        "n_unique_large_test":  len(large_freq_te),
        "code_summary_train": code_summary_tr,
        "cross_split_consistency": consistency,
        "corr_has_large_vs_attr3": float(corr_large_a3),
        "corr_has_large_vs_attr6": float(corr_large_a6),
        "corr_n_large_vs_attr3":   float(corr_nlarge_a3),
        "top_predictive_for_a3": sorted(
            [(c, s["attr3_mean"], s["attr3_std"], s["n"]) for c, s in code_summary_tr.items()],
            key=lambda x: -x[1]
        )[:15],
    }


# ============================================================
# SECTION 4 — REGIME DEEP DIVE
# ============================================================
def analyze_regimes(rows_tr, rows_va, rows_te, y_tr, y_va, lens_tr, lens_va, lens_te):
    reg_tr = np.array([get_regime(r) for r in rows_tr])
    reg_va = np.array([get_regime(r) for r in rows_va])
    reg_te = np.array([get_regime(r) for r in rows_te])

    regime_shift = {
        "train": {int(j): float((reg_tr == j).mean()) for j in range(3)},
        "val":   {int(j): float((reg_va == j).mean()) for j in range(3)},
        "test":  {int(j): float((reg_te == j).mean()) for j in range(3)},
    }

    # Target distribution per regime (train)
    regime_targets = {}
    for rg in range(3):
        idx = np.where(reg_tr == rg)[0]
        if len(idx) == 0:
            continue
        regime_targets[rg] = {
            col: {
                "mean": float(np.mean(y_tr[idx, j])),
                "std":  float(np.std(y_tr[idx, j])),
                "median": float(np.median(y_tr[idx, j])),
            }
            for j, col in enumerate(TARGET_COLS)
        }

    # Seq length per regime
    regime_lens = {
        rg: {
            "train_mean": float(np.mean(lens_tr[reg_tr == rg])) if (reg_tr == rg).any() else 0,
            "val_mean":   float(np.mean(lens_va[reg_va == rg])) if (reg_va == rg).any() else 0,
            "test_mean":  float(np.mean(lens_te[reg_te == rg])) if (reg_te == rg).any() else 0,
        }
        for rg in range(3)
    }

    # Boss deep dive: structure of regime-2 sequences
    boss_tr = [rows_tr[i] for i in np.where(reg_tr == 2)[0]]
    boss_va = [rows_va[i] for i in np.where(reg_va == 2)[0]]
    boss_te = [rows_te[i] for i in np.where(reg_te == 2)[0]]

    # Where exactly is token 104 in boss sequences?
    pos104_in_boss = []
    for r in boss_tr:
        if 104 in r:
            pos104_in_boss.append(r.index(104))
    last_pos = [len(r) - 1 for r in boss_tr if len(r) > 0]

    # What tokens immediately precede 104?
    pre104_tokens = Counter()
    for r in boss_tr:
        for i, v in enumerate(r):
            if v == 104 and i > 0:
                pre104_tokens[r[i-1]] += 1

    # attr_6 distribution for boss
    boss_tr_idx = np.where(reg_tr == 2)[0]
    boss_va_idx = np.where(reg_va == 2)[0]
    a6_boss_tr = y_tr[boss_tr_idx, 5] if len(boss_tr_idx) else np.array([])
    a6_boss_va = y_va[boss_va_idx, 5] if len(boss_va_idx) else np.array([])

    # Boss suffix rule evaluation
    boss_a6_tr = y_tr[boss_tr_idx, 5]
    lkp_boss_l2 = majority_rule(boss_tr, boss_a6_tr, lambda r: tuple(r[-2:]) if len(r) >= 2 else None)
    lkp_boss_l3 = majority_rule(boss_tr, boss_a6_tr, lambda r: tuple(r[-3:]) if len(r) >= 3 else None)
    boss_a6_va = y_va[boss_va_idx, 5]
    boss_rule = {
        "last2_to_a6": eval_rule(boss_va, boss_a6_va, lkp_boss_l2, lambda r: tuple(r[-2:]) if len(r)>=2 else None, min_n=3, min_purity=1.0),
        "last3_to_a6": eval_rule(boss_va, boss_a6_va, lkp_boss_l3, lambda r: tuple(r[-3:]) if len(r)>=3 else None, min_n=3, min_purity=1.0),
    }

    return {
        "regime_shift": regime_shift,
        "regime_targets_train": regime_targets,
        "regime_lens": regime_lens,
        "boss_n_train": len(boss_tr),
        "boss_n_val":   len(boss_va),
        "boss_n_test":  len(boss_te),
        "boss_104_always_last": float(np.mean([r[-1] == 104 for r in boss_tr if r])),
        "boss_pre104_top5": pre104_tokens.most_common(5),
        "boss_a6_train_mean": float(np.mean(a6_boss_tr)) if len(a6_boss_tr) else 0,
        "boss_a6_val_mean":   float(np.mean(a6_boss_va)) if len(a6_boss_va) else 0,
        "boss_rule": boss_rule,
    }


# ============================================================
# SECTION 5 — POSITIONAL RULE ANALYSIS
# ============================================================
def analyze_positional_rules(rows_tr, rows_va, y_tr, y_va):
    rules = {
        # prefix → start date
        "f1→a1":   (lambda r: (r[0],) if len(r)>=1 else None, 0, 5, 0.95),
        "f2→a1":   (lambda r: tuple(r[:2]) if len(r)>=2 else None, 0, 10, 0.95),
        "f3→a1":   (lambda r: tuple(r[:3]) if len(r)>=3 else None, 0, 5, 0.95),
        "f3→a2":   (lambda r: tuple(r[:3]) if len(r)>=3 else None, 1, 10, 0.95),
        "f4→a2":   (lambda r: tuple(r[:4]) if len(r)>=4 else None, 1, 5,  1.00),
        # suffix → end date / factory
        "l2s→a6":  (lambda r: tuple(strip104(r)[-2:]) if len(strip104(r))>=2 else None, 5, 10, 0.95),
        "l3s→a6":  (lambda r: tuple(strip104(r)[-3:]) if len(strip104(r))>=3 else None, 5, 5,  1.00),
        "l2s→a45": None,   # handled separately (multi-output)
        "l3s→a4":  (lambda r: tuple(strip104(r)[-3:]) if len(strip104(r))>=3 else None, 3, 5, 1.00),
        "l3s→a5":  (lambda r: tuple(strip104(r)[-3:]) if len(strip104(r))>=3 else None, 4, 5, 1.00),
        # middle → attr_3
        "mid45→a3":  (lambda r: tuple(r[4:6]) if len(r)>=6 else None, 2, 5, 0.98),
        "rev67→a3":  (lambda r: tuple(r[-7:-5]) if len(r)>=7 else None, 2, 5, 0.98),
        "mid23→a3":  (lambda r: tuple(r[2:4]) if len(r)>=4 else None, 2, 5, 0.98),
        # full split pattern
        "full_seq→all": None,   # handled separately
    }

    results = {}
    for name, spec in rules.items():
        if spec is None:
            continue
        fn, col_idx, min_n, min_p = spec
        lkp = majority_rule(rows_tr, y_tr[:, col_idx], fn)
        res = eval_rule(rows_va, y_va[:, col_idx], lkp, fn, min_n=min_n, min_purity=min_p)
        # Also measure accuracy on val with purity >= 0.98
        lkp_high = {k: v for k, v in lkp.items() if v[1] >= 0.98}
        cov_high = sum(1 for r in rows_va if fn(r) in lkp_high)
        results[name] = {**res, "n_lookup_keys": len(lkp), "n_highpurity_keys": len(lkp_high)}

    # l2s→a45 (multi-output)
    lkp_a45 = defaultdict(list)
    for r, yy in zip(rows_tr, y_tr):
        s = strip104(r)
        if len(s) < 2: continue
        lkp_a45[tuple(s[-2:])].append((int(yy[3]), int(yy[4])))
    a45_det = {}
    for k, vals in lkp_a45.items():
        if len(vals) < 10: continue
        cnt = Counter(vals); best, n = cnt.most_common(1)[0]
        if n / len(vals) >= 0.90:
            a45_det[k] = (best, n / len(vals))
    cov_a45 = acc_a45 = 0
    for r, yy in zip(rows_va, y_va):
        s = strip104(r)
        k = tuple(s[-2:]) if len(s) >= 2 else None
        if k not in a45_det: continue
        cov_a45 += 1
        pred, _ = a45_det[k]
        acc_a45 += int(pred == (int(yy[3]), int(yy[4])))
    results["l2s→a45"] = {
        "coverage": cov_a45 / max(1, len(rows_va)),
        "accuracy_on_covered": acc_a45 / max(1, cov_a45),
        "covered_rows": cov_a45,
        "n_lookup_keys": len(a45_det),
    }

    # Full exact sequence lookup
    exact_lkp = {}
    for r, yy in zip(rows_tr, y_tr):
        k = tuple(r)
        if k not in exact_lkp:
            exact_lkp[k] = tuple(int(v) for v in yy)
    cov_exact = acc_exact = 0
    for r, yy in zip(rows_va, y_va):
        k = tuple(r)
        if k not in exact_lkp: continue
        cov_exact += 1
        acc_exact += int(exact_lkp[k] == tuple(int(v) for v in yy))
    results["full_exact"] = {
        "coverage": cov_exact / max(1, len(rows_va)),
        "accuracy_on_covered": acc_exact / max(1, cov_exact),
        "covered_rows": cov_exact,
        "n_lookup_keys": len(exact_lkp),
    }

    # Positional importance: for each position p, what is majority-rule accuracy for attr_1?
    pos_accuracy = {}
    for p in range(10):
        fn = lambda r, _p=p: (r[_p],) if len(r) > _p else None
        lkp = majority_rule(rows_tr, y_tr[:, 0], fn)
        res = eval_rule(rows_va, y_va[:, 0], lkp, fn, min_n=5, min_purity=0.90)
        pos_accuracy[f"pos{p}_f1"] = res

    return results, pos_accuracy


# ============================================================
# SECTION 6 — TARGET ANALYSIS
# ============================================================
def analyze_targets(Y_train, Y_val):
    corr_tr = Y_train[TARGET_COLS].corr().round(4)
    corr_va = Y_val[TARGET_COLS].corr().round(4)

    tv = {c: total_variation(
        Y_train[c].value_counts(normalize=True),
        Y_val[c].value_counts(normalize=True)
    ) for c in TARGET_COLS}

    # Month-specific: train skewed (months 3, 11, 12 dominant)?
    a1_tr = Y_train["attr_1"].value_counts(normalize=True).sort_index()
    a1_va = Y_val["attr_1"].value_counts(normalize=True).sort_index()

    duration = {}
    for name, ydf in [("train", Y_train), ("val", Y_val)]:
        start = (ydf["attr_1"] - 1) * 31 + ydf["attr_2"]
        end   = (ydf["attr_4"] - 1) * 31 + ydf["attr_5"]
        dur   = end - start
        duration[name] = {
            "mean": float(dur.mean()), "median": float(dur.median()),
            "neg_ratio": float((dur < 0).mean()),
            "zero_ratio": float((dur == 0).mean()),
        }

    equality = {
        "train_month_eq": float((Y_train["attr_1"] == Y_train["attr_4"]).mean()),
        "val_month_eq":   float((Y_val["attr_1"]   == Y_val["attr_4"]).mean()),
        "train_day_eq":   float((Y_train["attr_2"] == Y_train["attr_5"]).mean()),
        "val_day_eq":     float((Y_val["attr_2"]   == Y_val["attr_5"]).mean()),
    }

    # attr_3 / attr_6 uniformity test
    attr3_tr_counts = Y_train["attr_3"].value_counts().sort_index()
    attr3_expected  = len(Y_train) / 100.0
    uniformity_attr3 = float(attr3_tr_counts.std() / attr3_expected)

    return {
        "correlation_train": corr_tr.to_dict(),
        "correlation_val":   corr_va.to_dict(),
        "total_variation":   tv,
        "attr1_skew_train_top3": a1_tr.nlargest(3).to_dict(),
        "attr1_skew_val_top3":   a1_va.nlargest(3).to_dict(),
        "duration": duration,
        "equality": equality,
        "attr3_uniformity_cv": uniformity_attr3,
    }


# ============================================================
# SECTION 7 — DUPLICATE / LABEL QUALITY
# ============================================================
def analyze_quality(rows_tr, y_tr):
    key_labels = defaultdict(set)
    key_count  = Counter(tuple(r) for r in rows_tr)
    for r, yy in zip(rows_tr, y_tr):
        key_labels[tuple(r)].add(tuple(int(v) for v in yy))
    n_dup      = sum(1 for k, cnt in key_count.items() if cnt > 1 and len(key_labels[k]) == 1)
    n_conflict = sum(1 for v in key_labels.values() if len(v) > 1)
    return {
        "n_unique_sequences": len(key_labels),
        "n_duplicate_keys": n_dup,
        "n_conflicting_keys": n_conflict,
        "conflict_rate": n_conflict / max(1, len(key_labels)),
    }


# ============================================================
# PLOTTING
# ============================================================
def make_all_plots(out_dir, data):
    ensure_dir(out_dir)

    rows_tr = data["rows_tr"]; rows_va = data["rows_va"]; rows_te = data["rows_te"]
    lens_tr = data["lens_tr"]; lens_va = data["lens_va"]; lens_te = data["lens_te"]
    Y_train = data["Y_train"]; Y_val = data["Y_val"]
    reg_tr  = data["reg_tr"];  reg_va = data["reg_va"]; reg_te = data["reg_te"]
    y_tr    = data["y_tr"];    y_va   = data["y_va"]
    large   = data["large"]
    spec    = data["spec"]

    # ── FIG 1: Sequence length distribution ──────────────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=False)
    bins = np.arange(2, 68)
    for ax, (name, lens, col) in zip(axes, [
        ("Train (n=55K)", lens_tr, "#4C72B0"),
        ("Val   (n=40K)", lens_va, "#DD8452"),
        ("Test  (n=108K)", lens_te, "#55A868"),
    ]):
        ax.hist(lens, bins=bins, color=col, alpha=0.85, density=True)
        ax.axvline(np.mean(lens), color="red", lw=1.5, ls="--", label=f"μ={np.mean(lens):.1f}")
        ax.axvline(np.median(lens), color="black", lw=1.2, ls=":", label=f"med={np.median(lens):.1f}")
        ax.set_title(name, fontsize=11)
        ax.set_xlabel("Sequence length")
        ax.legend(fontsize=8)
    fig.suptitle("Fig 1 — Distribution shift: chuỗi test dài hơn train ~70%", fontsize=12, fontweight="bold")
    savefig(os.path.join(out_dir, "fig01_length_distribution.png"))

    # ── FIG 2: Regime shift ──────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(9, 5))
    labels = ["Regime 0\n(có 103)", "Regime 1\n(không 103, không 104)", "Regime 2 / Boss\n(có 104, không 103)"]
    x = np.arange(3); w = 0.25
    colors = ["#4C72B0", "#DD8452", "#55A868"]
    for split, regs, label_s, c in [
        ("train", reg_tr, "Train", "#4C72B0"),
        ("val",   reg_va, "Val",   "#DD8452"),
        ("test",  reg_te, "Test",  "#55A868"),
    ]:
        vals = [(regs == j).mean() for j in range(3)]
        offset = {"train": -w, "val": 0, "test": w}[split]
        bars = ax.bar(x + offset, vals, width=w, label=f"{label_s}", color=c, alpha=0.85)
        for bar, v in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                    f"{v:.1%}", ha="center", va="bottom", fontsize=8)
    ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=9)
    ax.set_ylabel("Tỷ lệ")
    ax.legend(); ax.set_ylim(0, 0.85)
    ax.set_title("Fig 2 — Regime shift cực mạnh: Boss (Regime 2) từ 7.6% → 64.2% ở test", fontweight="bold")
    savefig(os.path.join(out_dir, "fig02_regime_shift.png"))

    # ── FIG 3: Special token presence shift ──────────────────────────────────
    key_toks = [102, 103, 104, 105, 609]
    tok_labels = ["102\n(SEP_START)", "103\n(SEP_MAIN)", "104\n(END_BOSS)", "105\n(HEADER_B)", "609\n(ROUTE)"]
    fig, ax = plt.subplots(figsize=(11, 5))
    x = np.arange(len(key_toks)); w = 0.25
    for split, rows, label_s, c in [
        ("train", rows_tr, "Train", "#4C72B0"),
        ("val",   rows_va, "Val",   "#DD8452"),
        ("test",  rows_te, "Test",  "#55A868"),
    ]:
        vals = [token_presence(rows, t) for t in key_toks]
        offset = {"train": -w, "val": 0, "test": w}[split]
        ax.bar(x + offset, vals, width=w, label=label_s, alpha=0.85, color=c)
    ax.set_xticks(x); ax.set_xticklabels(tok_labels, fontsize=9)
    ax.set_ylabel("Tỷ lệ sample chứa token")
    ax.legend()
    ax.set_title("Fig 3 — Token đặc biệt: 103 giảm, 104 và 609 tăng mạnh ở test", fontweight="bold")
    savefig(os.path.join(out_dir, "fig03_special_token_shift.png"))

    # ── FIG 4: Large code → attr_3 mapping ──────────────────────────────────
    lc_summary = large["code_summary_train"]
    top_codes = sorted(lc_summary.items(), key=lambda x: x[1]["attr3_mean"])
    codes_plot = top_codes[:8] + top_codes[-8:]
    fig, ax = plt.subplots(figsize=(12, 5))
    xpos = np.arange(len(codes_plot))
    means = [v["attr3_mean"] for _, v in codes_plot]
    stds  = [v["attr3_std"]  for _, v in codes_plot]
    xlabels = [f"LC_{c}" for c, _ in codes_plot]
    bars = ax.bar(xpos, means, color=["#d62728" if m < 30 else "#2ca02c" if m > 65 else "#1f77b4" for m in means], alpha=0.85)
    ax.errorbar(xpos, means, yerr=stds, fmt="none", color="black", capsize=4, lw=1.5)
    ax.set_xticks(xpos); ax.set_xticklabels(xlabels, rotation=35, ha="right", fontsize=8)
    ax.axhline(50, color="gray", ls="--", lw=1, label="mean=50 (uniform)")
    ax.set_ylabel("attr_3 mean"); ax.set_ylim(0, 105)
    ax.legend()
    ax.set_title("Fig 4 — Large codes (>10K) là mã nhà máy: predict mạnh attr_3\n(xanh=tải cao, đỏ=tải thấp, consistent giữa train và val)", fontweight="bold")
    savefig(os.path.join(out_dir, "fig04_large_code_attr3.png"))

    # ── FIG 5: Cross-split consistency of large code → attr_3 ────────────────
    consistency = large["cross_split_consistency"]
    if consistency:
        codes_c = sorted(consistency.items(), key=lambda x: -x[1]["tr_mean_a3"])[:20]
        fig, ax = plt.subplots(figsize=(12, 5))
        xp = np.arange(len(codes_c))
        tr_means = [v["tr_mean_a3"] for _, v in codes_c]
        va_means = [v["va_mean_a3"] for _, v in codes_c]
        ax.plot(xp, tr_means, "o-", label="Train mean attr_3", lw=1.5)
        ax.plot(xp, va_means, "s--", label="Val mean attr_3", lw=1.5)
        ax.set_xticks(xp); ax.set_xticklabels([f"LC_{c}" for c, _ in codes_c], rotation=35, ha="right", fontsize=7)
        ax.set_ylabel("attr_3 mean"); ax.legend()
        ax.set_title("Fig 5 — Large code → attr_3 signal cực kỳ ổn định qua train/val\n(Train và Val gần như trùng khớp → feature không bị leak)", fontweight="bold")
        savefig(os.path.join(out_dir, "fig05_large_code_consistency.png"))

    # ── FIG 6: Positional rule coverage / accuracy ───────────────────────────
    pos_rules = data["pos_results"]
    rule_names = [k for k in pos_rules if pos_rules[k]["coverage"] > 0.001]
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    for ax, metric, title, col in [
        (axes[0], "coverage", "Coverage trên val", "#4C72B0"),
        (axes[1], "accuracy_on_covered", "Accuracy trên phần covered", "#DD8452"),
    ]:
        vals = [pos_rules[n][metric] for n in rule_names]
        yp = np.arange(len(rule_names))
        bars = ax.barh(yp, vals, color=col, alpha=0.85)
        ax.set_yticks(yp); ax.set_yticklabels(rule_names, fontsize=9)
        ax.set_xlabel(metric); ax.set_xlim(0, 1.05)
        ax.axvline(0.95, color="red", ls="--", lw=1, label="95%")
        ax.legend(fontsize=8)
        ax.set_title(title, fontweight="bold")
        for bar, v in zip(bars, vals):
            ax.text(v + 0.01, bar.get_y() + bar.get_height()/2, f"{v:.1%}", va="center", fontsize=8)
    fig.suptitle("Fig 6 — Rule memory train→val: prefix/suffix gần-deterministic", fontsize=12, fontweight="bold")
    savefig(os.path.join(out_dir, "fig06_rule_coverage_accuracy.png"))

    # ── FIG 7: attr_1 month distribution drift ───────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(13, 4))
    months = np.arange(1, 13)
    for ax, (col_s, col_e, title) in zip(axes, [
        ("attr_1", "attr_4", "Tháng bắt đầu (attr_1) và kết thúc (attr_4)"),
    ] * 2):
        for col, ls, lbl in [("attr_1", "-", "attr_1 (start)"), ("attr_4", "--", "attr_4 (end)")]:
            tr = Y_train[col].value_counts(normalize=True).sort_index()
            va = Y_val[col].value_counts(normalize=True).sort_index()
            style = ls
            ax.plot(months, [tr.get(m, 0) for m in months], style, marker="o", lw=1.5, label=f"Train {lbl}")
            ax.plot(months, [va.get(m, 0) for m in months], style, marker="s", lw=1.5, ls=":", label=f"Val {lbl}")
        ax.set_xlabel("Tháng"); ax.set_ylabel("Tỷ lệ"); ax.legend(fontsize=7)
        ax.set_title(f"Fig 7 — Drift tháng: train lệch mạnh vào T3, T11, T12", fontweight="bold")
        break
    axes[1].axis("off")
    # Second subplot: attr_3 distribution comparison
    ax2 = fig.add_subplot(1, 2, 2)
    bins99 = np.arange(0, 101, 5)
    ax2.hist(Y_train["attr_3"], bins=bins99, density=True, alpha=0.6, label="Train attr_3", color="#4C72B0")
    ax2.hist(Y_val["attr_3"],   bins=bins99, density=True, alpha=0.6, label="Val attr_3",   color="#DD8452")
    ax2.set_xlabel("attr_3 value (0–99)"); ax2.set_ylabel("Density")
    ax2.legend(); ax2.set_title("Fig 7b — attr_3 gần uniform (0–99), không skew", fontweight="bold")
    savefig(os.path.join(out_dir, "fig07_month_and_attr3_distribution.png"))

    # ── FIG 8: Target correlation heatmap ────────────────────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    for ax, ydf, title in zip(axes, [Y_train, Y_val], ["Train", "Val"]):
        corr = ydf[TARGET_COLS].corr().values
        im = ax.imshow(corr, vmin=-0.15, vmax=1.0, cmap="RdYlGn")
        ax.set_xticks(range(6)); ax.set_xticklabels(TARGET_COLS, rotation=45, ha="right")
        ax.set_yticks(range(6)); ax.set_yticklabels(TARGET_COLS)
        ax.set_title(f"Fig 8 — Correlation {title}", fontweight="bold")
        for i in range(6):
            for j in range(6):
                ax.text(j, i, f"{corr[i,j]:.2f}", ha="center", va="center", fontsize=8,
                        color="white" if abs(corr[i,j]) > 0.6 else "black")
    plt.colorbar(im, ax=axes.tolist(), shrink=0.8)
    savefig(os.path.join(out_dir, "fig08_target_correlation.png"))

    # ── FIG 9: Seq length vs attr_2 / attr_5 scatter (sampled) ─────────────
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    lens_arr = lens_tr
    idx_sample = np.random.choice(len(lens_arr), min(5000, len(lens_arr)), replace=False)
    for ax, col, j in [(axes[0], "attr_2", 1), (axes[1], "attr_5", 4)]:
        ax.scatter(lens_arr[idx_sample], y_tr[idx_sample, j], alpha=0.15, s=8, color="#4C72B0")
        corr = np.corrcoef(lens_arr, y_tr[:, j])[0, 1]
        ax.set_xlabel("Seq length"); ax.set_ylabel(col)
        ax.set_title(f"Fig 9 — seq_len vs {col} (r={corr:.3f})\nChuỗi dài → ngày lớn hơn", fontweight="bold")
    savefig(os.path.join(out_dir, "fig09_seqlen_vs_day.png"))

    # ── FIG 10: perfect_f1 predictors ────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(10, 4))
    pf1 = spec["perfect_f1_predictors"]
    codes_sorted = sorted(pf1.items(), key=lambda x: x[1]["predicted_month"])
    xp = np.arange(len(codes_sorted))
    ax.bar(xp, [v["predicted_month"] for _, v in codes_sorted], color="#4C72B0", alpha=0.85)
    ax.set_xticks(xp)
    ax.set_xticklabels([f"code={c}\n(n={v['n_train']})" for c, v in codes_sorted], rotation=35, ha="right", fontsize=8)
    ax.set_ylabel("attr_1 dự đoán (tháng)")
    ax.set_title("Fig 10 — 10 mã feature_1 quyết định hoàn toàn tháng bắt đầu (acc=100%)\nPure deterministic: không cần model, chỉ cần lookup", fontweight="bold")
    savefig(os.path.join(out_dir, "fig10_perfect_f1_predictors.png"))

    print(f"  → 10 biểu đồ đã lưu vào {out_dir}/")


# ============================================================
# MARKDOWN REPORT
# ============================================================
def build_report(summary, out_path):
    R = []
    A = R.append

    A("# EDA CHUYÊN SÂU DF26 — Phân tách nghiêm ngặt Train / Validation\n")
    A("> **Nguyên tắc**: Toàn bộ insight được rút ra trên train, kiểm chứng trên val. "
      "Không trộn hai tập ở bất kỳ bước nào.\n")

    A("---\n")
    A("## 1. Quy mô và cấu trúc dữ liệu\n")
    ls = summary["len_stats"]
    A(f"| Split | N | Mean len | Median | P90 | P95 | Max |\n"
      f"|-------|---|----------|--------|-----|-----|-----|\n"
      f"| Train | 55,000 | {ls['train']['mean']:.1f} | {ls['train']['median']:.0f} | "
      f"{ls['train']['p90']:.0f} | {ls['train']['p95']:.0f} | {ls['train']['max']} |\n"
      f"| Val   | 40,000 | {ls['val']['mean']:.1f} | {ls['val']['median']:.0f} | "
      f"{ls['val']['p90']:.0f} | {ls['val']['p95']:.0f} | {ls['val']['max']} |\n"
      f"| Test  | 108,673 | {ls['test']['mean']:.1f} | {ls['test']['median']:.0f} | "
      f"{ls['test']['p90']:.0f} | {ls['test']['p95']:.0f} | {ls['test']['max']} |\n")
    A("**Insight 1 — Distribution shift mạnh nhất nằm ở độ dài chuỗi.** "
      f"Test dài hơn train khoảng 70% theo giá trị trung bình "
      f"({ls['test']['mean']:.1f} vs {ls['train']['mean']:.1f}). "
      "Mô hình dùng absolute positional embedding thuần sẽ gặp OOD khi inference. "
      "Reverse positional embedding và relative position là bắt buộc.\n")

    A("---\n")
    A("## 2. Phân tích token đặc biệt — Taxonomy 3 tầng\n")
    A("### Tầng 1 — Structural tokens (cấu trúc phân đoạn)\n")
    spec_data = summary["special_tokens"]
    for tok, desc in STRUCT_TOKENS.items():
        tr = spec_data["train"].get(tok, {})
        va = spec_data["val"].get(tok, {})
        te = spec_data["test"].get(tok, {})
        A(f"**Token {tok}** (`{desc}`)\n")
        A(f"- Xuất hiện: Train={pct(tr.get('pct_has',0))}, "
          f"Val={pct(va.get('pct_has',0))}, Test={pct(te.get('pct_has',0))}\n")
        if tr.get('pct_first'):
            A(f"- Đứng đầu chuỗi: {pct(tr['pct_first'])} (train)\n")
        if tr.get('pct_last'):
            A(f"- Đứng cuối chuỗi: {pct(tr['pct_last'])} (train)\n")
        if tr.get('mean_rel_position') is not None:
            A(f"- Vị trí tương đối trung bình: {tr['mean_rel_position']:.3f} (0=đầu, 1=cuối)\n")
        A("\n")

    pos103 = spec_data.get("pos103_relative_distribution", {})
    if pos103.get("mean") is not None:
        A(f"**Token 103 (SEP_MAIN) — vị trí trong chuỗi:**\n"
          f"- Mean relative position: **{pos103['mean']:.3f}** (thường nằm ở giữa-cuối)\n"
          f"- Median relative position: **{pos103['median']:.3f}**\n"
          f"- % nằm ở nửa đầu chuỗi: **{pct(pos103['pct_in_first_half'])}**\n\n"
          "→ Token 103 phân tách prefix (thông tin start-date) khỏi suffix (thông tin end-date + factory). "
          "Segment trước 103 predict attr_1/2, segment sau 103 predict attr_4/5/6.\n")

    boss_104 = spec_data.get("boss_104_position", {})
    A(f"\n**Token 104 (END_BOSS) — boss regime analysis:**\n"
      f"- 104 luôn là token cuối cùng: **{pct(boss_104.get('boss_pct_104_at_last', summary['regimes'].get('boss_104_always_last', 0)))}**\n"
      f"- Điều này xác nhận 104 là terminator token, không phải action code thông thường.\n\n")

    A("### Tầng 2 — Flag/context tokens (mã loại hành động)\n")
    A("Token range `97–179` (25 giá trị duy nhất) là **action-type codes**: mô tả loại tương tác, "
      "không phải sản phẩm cụ thể. Đặc biệt:\n")
    pf1 = spec_data.get("perfect_f1_predictors", {})
    for code, info in sorted(pf1.items(), key=lambda x: x[1]["predicted_month"]):
        A(f"- **Code {code}** → attr_1 = tháng **{info['predicted_month']}** với accuracy 100% "
          f"(n={info['n_train']:,} mẫu train)\n")
    A("\n**Insight 2 — 10 mã feature_1 quyết định hoàn toàn tháng bắt đầu.** "
      "Đây là pure deterministic rule, không cần model. "
      "Chúng cover ~50% data train và phải được xử lý qua lookup trước khi model prediction.\n")

    A("\n### Tầng 3 — Routing tokens (token định hướng regime)\n")
    r609 = spec_data.get("token_609_routing", {})
    A(f"**Token 609 (ROUTE_609):**\n"
      f"- % sample có 609: Train={pct(spec_data['train'].get(609,{}).get('pct_has',0))}, "
      f"Val={pct(spec_data['val'].get(609,{}).get('pct_has',0))}, "
      f"Test={pct(spec_data['test'].get(609,{}).get('pct_has',0))}\n"
      f"- Khi xuất hiện, 609 luôn đứng đầu: **{pct(r609.get('pct_609_first',0))}**\n"
      f"- Khi có 609, không có 103: **{pct(r609.get('pct_no_103_when_609',0))}** → "
      "xác nhận 609 là routing token cho regime 1 (no-split mode)\n"
      f"- Khi có 609, không có 104: **{pct(r609.get('pct_no_104_when_609',0))}** → "
      "không phải boss\n\n")

    A("---\n")
    A("## 3. Regime — Distribution shift cực mạnh\n")
    reg_data = summary["regimes"]
    rs = reg_data["regime_shift"]
    A("| Regime | Mô tả | Train | Val | Test |\n"
      "|--------|-------|-------|-----|------|\n"
      f"| 0 | Chuỗi có 103 (split) | {pct(rs['train'][0])} | {pct(rs['val'][0])} | {pct(rs['test'][0])} |\n"
      f"| 1 | Không 103, không 104 | {pct(rs['train'][1])} | {pct(rs['val'][1])} | {pct(rs['test'][1])} |\n"
      f"| 2 (Boss) | Có 104, không 103 | {pct(rs['train'][2])} | {pct(rs['val'][2])} | {pct(rs['test'][2])} |\n")
    A("\n**Insight 3 — Test bị boss regime thống trị.** "
      f"Regime 2 tăng từ {pct(rs['train'][2])} → {pct(rs['val'][2])} → **{pct(rs['test'][2])}**. "
      "Đây không phải distribution shift nhỏ — đây là thay đổi paradigm. "
      "Mô hình nào không có dedicated boss logic sẽ fail trên phần lớn test set.\n")

    A("\n### Boss regime deep dive\n")
    A(f"- Token 104 luôn là token cuối trong boss sequences: "
      f"**{pct(reg_data.get('boss_104_always_last', 0))}**\n")
    A(f"- Top token xuất hiện ngay trước 104: "
      f"{reg_data.get('boss_pre104_top5', [])}\n")
    A(f"- Mean attr_6 trong boss: train={reg_data['boss_a6_train_mean']:.2f}, "
      f"val={reg_data['boss_a6_val_mean']:.2f}\n")
    br = reg_data["boss_rule"]
    A(f"- Rule boss_last2→attr_6: coverage={pct(br['last2_to_a6']['coverage'])}, "
      f"accuracy={pct(br['last2_to_a6']['accuracy_on_covered'])}\n")
    A(f"- Rule boss_last3→attr_6: coverage={pct(br['last3_to_a6']['coverage'])}, "
      f"accuracy={pct(br['last3_to_a6']['accuracy_on_covered'])}\n\n")
    A("**Insight 4 — Với boss regime, suffix (raw last 2–3 tokens kể cả 104) "
      "predict attr_6 với accuracy gần tuyệt đối.** "
      "Đây là rule memory quan trọng nhất cho test set.\n")

    A("---\n")
    A("## 4. Large codes (>10,000) — Mã nhà máy / sản phẩm\n")
    lc = summary["large_codes"]
    A(f"- Số large code unique trong train: **{lc['n_unique_large_train']}**\n"
      f"- Số large code unique trong test: **{lc['n_unique_large_test']}**\n"
      f"- Correlation: có large code vs attr_3 = **{lc['corr_has_large_vs_attr3']:.4f}**\n"
      f"- Correlation: n_large trong chuỗi vs attr_3 = **{lc['corr_n_large_vs_attr3']:.4f}**\n\n")
    A("**Top large codes theo mean attr_3 (train, nhất quán với val):**\n\n")
    A("| Large Code | N train | attr_3 mean | attr_3 std | Diễn giải |\n"
      "|------------|---------|-------------|------------|------|\n")
    for code, m, s, n in lc["top_predictive_for_a3"][:10]:
        desc = LARGE_CODE_KNOWN.get(code, "")
        A(f"| {code} | {n:,} | {m:.1f} | {s:.1f} | {desc} |\n")
    A("\n**Insight 5 — Large codes encode thông tin nhà máy trực tiếp.** "
      "Một số code predict attr_3 với mean cách xa 50 (uniform), "
      "và pattern này ổn định giữa train và val (cross-split consistency). "
      "Đây là feature quan trọng nhất bị bỏ sót trong các model baseline. "
      "Aggregate embedding của các large codes trong chuỗi là signal trực tiếp cho attr_3/6.\n")

    A("---\n")
    A("## 5. Positional rule memory — Coverage và Accuracy\n")
    pos_r = summary["pos_results"]
    A("| Rule | Coverage val | Accuracy trên covered | N keys |\n"
      "|------|-------------|----------------------|--------|\n")
    for name, v in sorted(pos_r.items(), key=lambda x: -x[1]["accuracy_on_covered"]):
        A(f"| {name} | {pct(v['coverage'])} | {pct(v['accuracy_on_covered'])} | "
          f"{v.get('n_lookup_keys', '—')} |\n")
    A("\n**Insight 6 — Cấu trúc phân đoạn là xương sống của bài toán.** "
      "Prefix (3–4 token đầu) predict tháng/ngày bắt đầu với accuracy rất cao trên phần covered. "
      "Suffix stripped (2–3 token cuối sau khi bỏ 104) predict attr_4/5/6. "
      "Middle window (position 4–5 hoặc reverse 6–7) predict attr_3. "
      "Rule memory 3 tầng (exact → high-purity → soft-blend) có thể override "
      "model prediction cho phần lớn sample.\n")

    A("---\n")
    A("## 6. Target distribution và drift\n")
    tgt = summary["targets"]
    A("**Total variation distance train vs val:**\n")
    for c, tv in tgt["total_variation"].items():
        A(f"- {c}: **{tv:.4f}**\n")
    A(f"\n**Tháng bắt đầu (attr_1) bị skew trong train:** "
      f"{tgt['attr1_skew_train_top3']}\n"
      f"**Val phân phối đều hơn:** {tgt['attr1_skew_val_top3']}\n")
    A(f"\n**attr_3 uniformity CV:** {tgt['attr3_uniformity_cv']:.4f} "
      "(gần 0 = uniform → regression thuần không đủ nắm bắt pattern)\n")
    A(f"\n**Duration timeline:**\n"
      f"- Train: mean={tgt['duration']['train']['mean']:.1f}, "
      f"neg_ratio={pct(tgt['duration']['train']['neg_ratio'])}, "
      f"zero_ratio={pct(tgt['duration']['train']['zero_ratio'])}\n"
      f"- Val: mean={tgt['duration']['val']['mean']:.1f}, "
      f"neg_ratio={pct(tgt['duration']['val']['neg_ratio'])}\n")
    A("\n**Insight 7 — ~44% duration âm nếu tính linear.** "
      "Date encoding có tính chu kỳ / operational, không phải calendar thuần. "
      "Không nên áp hard constraint end>=start.\n")

    A(f"\n**Correlation đáng chú ý (train):** "
      f"corr(attr_2, attr_5)={tgt['correlation_train']['attr_2']['attr_5']:.3f} — "
      f"ngày bắt đầu và kết thúc có liên hệ vừa. "
      f"corr(attr_3, attr_6)={tgt['correlation_train']['attr_3']['attr_6']:.3f} — "
      f"**hai chỉ số nhà máy gần như độc lập nhau** → phải có head riêng cho từng cái.\n")

    A("---\n")
    A("## 7. Label quality\n")
    q = summary["quality"]
    A(f"- Unique sequences train: **{q['n_unique_sequences']:,}**\n"
      f"- Duplicate keys (cùng sequence, cùng label): **{q['n_duplicate_keys']:,}**\n"
      f"- Conflicting keys (cùng sequence, khác label): **{q['n_conflicting_keys']:,}** "
      f"(conflict rate: {pct(q['conflict_rate'])})\n\n"
      "**Nhãn train sạch** — không có xung đột có nghĩa là dữ liệu được tạo bởi quy luật xác định, "
      "không phải human annotation. Điều này củng cố hướng rule memory.\n")

    A("---\n")
    A("## 8. Business logic ẩn và hàm ý mô hình hóa\n")
    A("Từ toàn bộ EDA, bức tranh tổng thể như sau:\n\n"
      "1. **Mỗi sample = một chuỗi sự kiện giao dịch** với cấu trúc phân đoạn rõ: "
      "prefix → sep (103) → suffix. Không phải chuỗi ngẫu nhiên.\n\n"
      "2. **Prefix encode thời điểm bắt đầu** (attr_1, attr_2). "
      "Token feature_1 đặc biệt quyết định tháng hoàn toàn cho ~50% mẫu.\n\n"
      "3. **Suffix encode thời điểm kết thúc và factory** (attr_4, attr_5, attr_6). "
      "Boss regime (không có 103) dùng raw suffix kể cả token 104.\n\n"
      "4. **Middle window encode chỉ số nhà máy đầu** (attr_3). "
      "Các large codes (>10K) trong chuỗi là mã nhà máy, "
      "predict attr_3 với range cực rộng (10→73) và ổn định cross-split.\n\n"
      "5. **Test bị thống trị bởi boss regime (64.2%)** trong khi train chỉ 7.6%. "
      "Đây là lý do chính khiến base model fail trên test — "
      "chúng không có logic riêng cho boss.\n\n"
      "**Hàm ý trực tiếp:**\n"
      "- Cần regime-aware expert: prefix expert, middle expert, suffix/boss expert\n"
      "- Cần large code embedding aggregate vào branch attr_3/6\n"
      "- Cần rule memory 3 tầng: exact full → high-purity prefix/suffix → soft-blend middle\n"
      "- Cần dual-head (regression + distribution) cho attr_3/6 vì chúng có pattern "
      "vừa liên tục vừa near-deterministic\n"
      "- Tuyệt đối không dùng absolute positional embedding thuần: "
      "test sequences dài hơn 70% so với train\n")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(R))
    print(f"  → Báo cáo Markdown: {out_path}")


# ============================================================
# MAIN
# ============================================================
def main():
    data_dir = find_data_dir()
    ensure_dir(OUT_DIR)
    print(f"Data dir: {data_dir}\nOutput : {OUT_DIR}\n")

    X_train, X_val, X_test, Y_train, Y_val, feat_cols = load_data(data_dir)
    print("Loading sequences...")
    rows_tr, lens_tr = get_rows_lens(X_train, feat_cols)
    rows_va, lens_va = get_rows_lens(X_val,   feat_cols)
    rows_te, lens_te = get_rows_lens(X_test,  feat_cols)
    y_tr = Y_train[TARGET_COLS].to_numpy(dtype=np.int64)
    y_va = Y_val[TARGET_COLS].to_numpy(dtype=np.int64)
    reg_tr = np.array([get_regime(r) for r in rows_tr])
    reg_va = np.array([get_regime(r) for r in rows_va])
    reg_te = np.array([get_regime(r) for r in rows_te])

    len_stats = {
        split: {
            "n": int(lens.size), "min": int(lens.min()), "mean": float(lens.mean()),
            "median": float(np.median(lens)), "p90": float(np.percentile(lens, 90)),
            "p95": float(np.percentile(lens, 95)), "max": int(lens.max()),
        }
        for split, lens in [("train", lens_tr), ("val", lens_va), ("test", lens_te)]
    }

    print("Analyzing special tokens...")
    spec = analyze_special_tokens(rows_tr, rows_va, rows_te, y_tr, y_va)

    print("Analyzing large codes...")
    large = analyze_large_codes(rows_tr, rows_va, rows_te, y_tr, y_va)

    print("Analyzing regimes...")
    reg_result = analyze_regimes(rows_tr, rows_va, rows_te, y_tr, y_va, lens_tr, lens_va, lens_te)

    print("Analyzing positional rules...")
    pos_results, pos_acc = analyze_positional_rules(rows_tr, rows_va, y_tr, y_va)

    print("Analyzing targets...")
    tgt = analyze_targets(Y_train, Y_val)

    print("Analyzing label quality...")
    quality = analyze_quality(rows_tr, y_tr)

    # Attach boss_104_always_last to reg_result for report
    reg_result["boss_104_always_last"] = spec.get("boss_104_position", {}).get("pct_104_at_last", 0)

    summary = {
        "len_stats": len_stats,
        "special_tokens": spec,
        "large_codes": large,
        "regimes": reg_result,
        "pos_results": pos_results,
        "pos_accuracy_by_position": pos_acc,
        "targets": tgt,
        "quality": quality,
    }

    json_path = os.path.join(OUT_DIR, "eda_summary.json")
    with open(json_path, "w", encoding="utf-8") as f:
        # Convert numpy types for JSON
        def convert(o):
            if isinstance(o, (np.integer,)): return int(o)
            if isinstance(o, (np.floating,)): return float(o)
            if isinstance(o, np.ndarray): return o.tolist()
            if isinstance(o, tuple): return list(o)
            raise TypeError(f"Not serializable: {type(o)}")
        json.dump(summary, f, ensure_ascii=False, indent=2, default=convert)
    print(f"  → JSON summary: {json_path}")

    print("Generating plots...")
    make_all_plots(OUT_DIR, {
        "rows_tr": rows_tr, "rows_va": rows_va, "rows_te": rows_te,
        "lens_tr": lens_tr, "lens_va": lens_va, "lens_te": lens_te,
        "Y_train": Y_train, "Y_val": Y_val,
        "reg_tr": reg_tr, "reg_va": reg_va, "reg_te": reg_te,
        "y_tr": y_tr, "y_va": y_va,
        "large": large, "spec": spec,
        "pos_results": pos_results,
    })

    print("Building report...")
    build_report(summary, os.path.join(OUT_DIR, "EDA_Report_DF26_Deep.md"))

    print("\n=== DONE ===")
    print(f"Output folder : {OUT_DIR}/")
    print("Key files:")
    print("  eda_summary.json")
    print("  EDA_Report_DF26_Deep.md")
    for i in range(1, 11):
        print(f"  fig{i:02d}_*.png")


if __name__ == "__main__":
    main()
